name: speech_recogntion
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3
  speech_to_text: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: TiltNeon
      fonts:
        - asset: assets/font/TiltNeon.ttf
